### ISSUE TITLE
Query param ?sort= not sending property properly if property is dasherized

### ISSUE THREAD

**Issue by Aaronfischer** [caxiam/ember-table-jsonapi#13]
Note: Originally, we used underscores to separate attribute names. To ensure we keep this open to other API's I'll need to make a few changes in the `setSort` method to ensure we can use underscores or dashes.

**Comment by morgan** [comment]
Need to isolate a method name that properly defines the context. Single responsibility.

**Comment by Aaronfischer** [comment]
Sorry, I'm not following what you are suggesting.
