### ISSUE TITLE
Create adapter methods for serializing and normalizing query/filter/pagination/sort

### ISSUE THREAD

**Issue by Aaronfischer** [caxiam/ember-table-jsonapi#16]

**Comment by Aaronfischer** [comment]
@morgan Feeling a lot better with how this is coming together!

One outstanding issue I may have to break from though...
We are serializing/normalizing right before and right after the request, for the filter sub-components to work they need to properly match up the filter[property] to know when to delete the filter[property]:

```js
        ...
        filter[property] = value;

        // Remove filter if value is an empty string
        // to prevent empty request from being sent
        if (value === '' || value === null) {
            delete filter[property];
        }
        ...
```

I think the issue is that in some cases the property is still dasherized and was not camelized, perhaps an issue with two-way binding? 
After logging all the things I've found that the issue only occurs when using the "global" filters, only when the filters are not used within the direct context of the component but used within the `isHeader` yield.

When I use `var query = this.get('query') || this.get('parentView.query'),` to grab the query, it seems that `parentView.query` is getting an outdated version of query (one that is still dasherized and has not been camelized).
Do you know of a different way to grab the parent context beyond parentView? I'll dig into this at another time, I need to shut down the engines for now.

**Comment by morgan** [comment]
@Aaronfischer Sounds like a race condition. Trace your promises and also make sure you understand where in the Ember run loop you are. That `setModel` method seems overly complex. Recommend console logging throughout a render and watching the behavior.

**Comment by Aaronfischer** [comment]
@morgan So after logging the entire process out, its actually not a problem with the code but an oversight that we need to ensure we are keeping all filter property naming conventions "internally" as camelCase. 
So, fortunately a very simple fix, literally just make sure we are passing in the camelCased property to the global filters properly. :+1: 
I've also updated the documentation to note this as well.
